# Generated by Django 3.2.9 on 2021-12-06 11:04

from django.db import migrations
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
