# Generated by Django 4.0 on 2021-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='photo'),
        ),
    ]
