# Generated by Django 4.0 on 2021-12-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
        ('subscribe_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberequest',
            name='desired_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_requests', to='user.user'),
        ),
        migrations.AlterField(
            model_name='subscriberequest',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_requests', to='user.user'),
        ),
    ]
