# Generated by Django 4.0 on 2021-12-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_page_followers_alter_page_subscriptions'),
        ('subscribe_request', '0004_remove_subscriberequest_desired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberequest',
            name='initiator',
        ),
        migrations.AddField(
            model_name='subscriberequest',
            name='initiator_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_requests', to='page.page'),
        ),
        migrations.AlterField(
            model_name='subscriberequest',
            name='desired_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_requests', to='page.page'),
        ),
    ]
