# Generated by Django 4.0 on 2021-12-17 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0003_alter_page_unblock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(related_name='follow_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribe_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
